spring:
  profiles:
    active: local

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

jwt:
  header: Authorization
  secret: mySecret
  expiration: 120000
  route:
    authentication:
      path: auth
      refresh: refresh


sms:
  apiKey : 9VNpCj4ER+A-kBJuRsqUzpxkLo7LCHvHBhhSODAfhd
  sender : TXTLCL
  
server:
  port: 8098