server:
  port: 8099

# Postgres db configuration
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.132:5432/aisdb
    username: ais
    password: ais
    testOnBorrow: true
    validationQuery: select 1 
    validationInterval: 30000
    maxActive: 100
    maxIdle: 100
    minIdle: 10
    initialSize: 0
    maxWait: 30000
    testOnReturn: false
    testWhileIdle: false
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false
  jpa:
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  
      
tcp:
  host: 
    name: 111.93.16.246
    port: 45567
aws:
  accesskey: AKIAJBC5KTK2R5DPCK7A
  secretaccesskey: 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
  region : us-east-1
  sns:
    topicArn: arn:aws:sns:us-east-1:337579094154:arai
    topicName: arai
    SMSType: Promotional
    phoneNumberRegex: ^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$
    senderIDRegex: test
    senderID: GreenArk16
